import { Organization } from './types';

export const ALL_DATA: Organization[] = [
  {
    id: 1,
    name: "Automotive Investment Scheme (AIS)",
    website: "http://www.thedtic.gov.za/financial-and-non-financial-support/incentives/automotive-investment-scheme/",
    category: "Lean Enterprise Model",
    role: "Enabler",
    type: "Enabler",
    city: "National (Online/HQ)",
    province: "Nationwide",
    lat: -28.4793,
    lng: 24.6727,
    isPulseVerified: true
  },
  {
    id: 2,
    name: "FNB and WesBank Automotive Aftermarket Business Accelerator",
    website: "https://edgegrowth.incubatorportal.com/apply/aaba",
    category: "Acceleration Model",
    role: "Enabler",
    type: "Enabler",
    city: "National (Online/HQ)",
    province: "Nationwide",
    lat: -28.4793,
    lng: 24.6727,
    isPulseVerified: true
  },
  {
    id: 3,
    name: "UVU Africa",
    website: "https://uvuafrica.com/programmes/timbuktoo-creative-hub-ideation-incubation-programme/",
    category: "Acceleration Model",
    role: "Enabler",
    type: "Enabler",
    city: "National (Online/HQ)",
    province: "Nationwide",
    lat: -28.4793,
    lng: 24.6727,
    isPulseVerified: true
  },
  {
    id: 4,
    name: "Innovate Durban (SHEshisa Programme)",
    website: "https://www.innovate.durban/sheshisa/",
    category: "Acceleration Model",
    role: "Enabler",
    type: "Enabler",
    city: "Durban",
    province: "KwaZulu-Natal",
    lat: -29.8587,
    lng: 31.0218,
    isPulseVerified: true
  },
  {
    id: 5,
    name: "Sekhukhune TVET College",
    website: "http://www.incubatesekhukhune.co.za",
    category: "TVET Technology Trasfer Office",
    role: "Enabler",
    type: "Enabler",
    city: "Sekhukhune",
    province: "Limpopo",
    lat: -24.7735,
    lng: 29.9723,
    isPulseVerified: true
  },
  {
    id: 6,
    name: "NCDev Hub",
    website: "https://ncdev.co.za",
    category: "Business Development",
    role: "The central hub for Northern Cape innovation.",
    type: "Enabler",
    city: "Kimberley",
    province: "Northern Cape",
    lat: -28.738,
    lng: 24.760,
    isPulseVerified: true,
    email: "admin@ncdev.co.za",
    phone: "053 123 4567"
  },
  {
    id: 7,
    name: "Sishen Tech",
    website: "https://sishen.tech",
    category: "Manufacturing",
    role: "AI solutions for open cast mining.",
    type: "Innovator",
    city: "Kathu",
    province: "Northern Cape",
    lat: -27.7,
    lng: 23.0,
    isPulseVerified: true
  },
  {
    id: 8,
    name: "Karoo Lamb IoT",
    website: "https://karoolamb.io",
    category: "Agriculture",
    role: "Tracking sheep in the Karoo.",
    type: "Innovator",
    city: "De Aar",
    province: "Northern Cape",
    lat: -30.5,
    lng: 24.5,
    isPulseVerified: false
  },
  {
    id: 9,
    name: "Sol Plaatje University",
    website: "https://spu.ac.za",
    category: "Education & Skills",
    role: "Leading research and innovation hub in the NC.",
    type: "Knowledge",
    city: "Kimberley",
    province: "Northern Cape",
    lat: -28.741,
    lng: 24.757,
    isPulseVerified: true
  },
  {
    id: 10,
    name: "NC Dept of Economic Development",
    website: "https://nceda.co.za",
    category: "Support & Development",
    role: "Provincial government agency supporting business growth.",
    type: "Government",
    city: "Kimberley",
    province: "Northern Cape",
    lat: -29.125,
    lng: 25.506,
    isPulseVerified: true
  },
  {
    id: 11,
    name: "Kimberley Public Library (Free Wifi)",
    website: "https://www.solplaatje.org.za",
    category: "Public Resource",
    role: "Free public wifi and workspace.",
    type: "Infrastructure",
    city: "Kimberley",
    province: "Northern Cape",
    lat: -28.739,
    lng: 24.761,
    isPulseVerified: true,
    phone: "053 830 6111"
  },
  {
    id: 12,
    name: "Kathu 3D Printing Lab",
    website: "https://ncdev.co.za/labs",
    category: "Makerspace",
    role: "Public access to 3D printers and prototyping tools.",
    type: "Infrastructure",
    city: "Kathu",
    province: "Northern Cape",
    lat: -27.695,
    lng: 23.045,
    isPulseVerified: true,
    email: "labs@ncdev.co.za"
  },
  {
    id: 13,
    name: "Upington Community Hall",
    website: "https://www.dawning.gov.za",
    category: "Venue",
    role: "Large venue for community meetings and innovation workshops.",
    type: "Infrastructure",
    city: "Upington",
    province: "Northern Cape",
    lat: -28.447,
    lng: 21.242,
    isPulseVerified: false
  },
  {
    id: 14,
    name: "Sol Plaatje Stadium (Event Venue)",
    website: "https://www.solplaatje.org.za/stadium",
    category: "Venue",
    role: "Major sports and community event venue.",
    type: "Infrastructure",
    city: "Kimberley",
    province: "Northern Cape",
    lat: -28.745,
    lng: 24.755,
    isPulseVerified: true
  },
  {
    id: 15,
    name: "NC Power Grid Station",
    website: "https://www.eskom.co.za",
    category: "Power Station",
    role: "Key electrical infrastructure for the region.",
    type: "Infrastructure",
    city: "Kimberley",
    province: "Northern Cape",
    lat: -28.750,
    lng: 24.780,
    isPulseVerified: false
  },
  {
    id: 16,
    name: "Digital Hub Wifi Hotspot",
    website: "https://ncdev.co.za/wifi",
    category: "Public Resource",
    role: "High-speed public wifi hotspot in the city center.",
    type: "Infrastructure",
    city: "Kimberley",
    province: "Northern Cape",
    lat: -28.735,
    lng: 24.765,
    isPulseVerified: true
  }
];
